[package]
name = "hl-node-watcher"
version = "0.1.0"
edition = "2021"

[dependencies]
hyperliquid_rust_sdk = "0.5.0"
rayon = "1.10.0"
serde = "1.0.204"
ethers = "2.0.14"
serde_json = "1.0.120"
eyre = "0.6.12"
rmp-serde = "1.3.0"
notify = "6.1.1"
log = "0.4.22"
env_logger = "0.11.3"
